version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    ports:
      - "8084:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - DB_VENDOR=h2
    command: start-dev