version: '3.8'

services:
  api-gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    volumes:
      -  .:/app
    ports:
      - 8086:8086
    networks:
      b3-social-actions:
        ipv4_address: 10.0.20.20

networks:
  b3-social-actions:
    external: true
